services:

  main-db:
    image: postgres:16-alpine
    container_name: main-db
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      POSTGRES_PASSWORD: secret123
      # Set user to app to match user from template-infra (https://github.com/navapbc/template-infra)
      # This is also needed for the initial migration that alters defaut privileges to grant
      # table privileges to the app user (see /app/src/db/migrations/versions/2023_08_10_default_table_privileges.py)
      POSTGRES_USER: app
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  main-app:
    build:
      context: ./
      target: dev
      args:
        - RUN_UID=${RUN_UID:-4000}
        - RUN_USER=${RUN_USER:-app}
    command: ["poetry", "run", "flask", "--app", "src.app", "run", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    container_name: main-app
    env_file:
      - path: ./local.env
        required: true
      - path: ./override.env
        required: false
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - main-db

volumes:
  dbdata:


